// Package render is a pure function from the store to the Markdown status
// document (TDD 3). It renders a role-based
// summary table, a Submitter section split into Open / Stale / Merged / Closed
// tables, and a Reviewer section split by ball-holding (Awaiting Our Action /
// Open — Review Submitted) plus a Done table. The Markdown is never a source of
// truth and is never read back (POLICY; TDD 3.3): given an unchanged store and
// reference time the output is byte-identical except for the supplied Last
// Updated value (TDD 3.4).
package render

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/Jonathan-Improving/githubslashboard/model"
)

// Cell/section emoji vocabulary for the rendered document.
const (
	// Summary table column emojis.
	sumOpen   = "🟢"
	sumStale  = "🟡"
	sumMerged = "✅"
	sumClosed = "🔴"

	// Submitter bucket section emojis.
	secOpen   = "💡"
	secStale  = "☠"
	secMerged = "📦"
	secClosed = "⛔"

	// Action-Needed / Our-Review cell markers.
	markPending   = "⏳" // pending some action, not on us (awaiting review, unassigned, blocked)
	markBackForth = "🔄" // active back-and-forth (author iterating, changes requested)

	// markCIFailing flags a submitter PR whose build is red. It leads the cell
	// *in addition to* whatever the action says, because CI state and review state
	// are orthogonal facts and neither may hide the other (TDD 4.11).
	markCIFailing = "🚧"

	// Reviewer Done outcome markers.
	outcomeMerged = "🎉 MERGED"
	outcomeClosed = "🚪 CLOSED"

	// elevatedMarker distinguishes an elevated-priority row (TDD 3.5).
	elevatedMarker = "🔺 "

	// unavailableNote is shown when no companion could be produced (TDD 4.5).
	unavailableNote = "_(unavailable)_"

	// generatedNotice warns that the document is machine-generated from the YAML
	// source of truth and is never read back, so any manual edit is lost on the
	// next run (TDD 3.3 — the Markdown is a pure sink).
	generatedNotice = "> ⚠️ **This file is generated by GithubSlashboard.** " +
		"It is rendered from the YAML source of truth on every run — any manual edits will be overwritten."
)

// dateLayout formats the Created / Merged / Closed date columns.
const dateLayout = "2006-01-02"

// closeReasonEmoji maps each close sub-reason to a deterministic glyph shown in
// the reviewer Done outcome. It is not LLM-inferred: close_reason is a finite
// enum (SCHEMA), so a fixed emoji per value stays consistent run to run. A
// reason with no mapping renders without an emoji.
var closeReasonEmoji = map[model.CloseReason]string{
	model.CloseReasonSuperseded: "♻️",
	model.CloseReasonCancelled:  "🗑️",
	model.CloseReasonStale:      "🕰️",
	model.CloseReasonInvalid:    "🚫",
}

// Render produces the full Markdown status document from the store's PRs and
// issues, the supplied Last Updated string (emitted verbatim, TDD 3.4), and a
// reference time used to compute ages. The document is titled for the tool rather
// than for PRs, since it tracks more than pull requests (TDD 8.6).
func Render(prs []model.PR, issues []model.Issue, lastUpdated string, now time.Time) string {
	var b strings.Builder

	b.WriteString("# 📋 GithubSlashboard\n\n")
	b.WriteString(fmt.Sprintf("_Last Updated: %s_\n\n", lastUpdated))
	b.WriteString(generatedNotice + "\n\n")

	submitters := filterRole(prs, model.RoleSubmitter)
	reviewers := filterRole(prs, model.RoleReviewer)

	writeSummaryTable(&b, submitters, reviewers, issues)

	b.WriteString("# Submitter: PRs I Authored\n\n")
	writeSubmitterSection(&b, submitters, now)

	// Horizontal rule separating the two role sections.
	b.WriteString("---\n\n")

	b.WriteString("# Reviewer: PRs I Reviewed\n\n")
	writeReviewerSection(&b, reviewers, now)

	// Horizontal rule separating the PR half of the document from the issues
	// half (TDD 8.6).
	b.WriteString("---\n\n")

	writeIssuesSection(&b, issues, now)

	return b.String()
}

// writeSummaryTable emits the at-a-glance summary: one row per PR role with
// counts per PR bucket, then one row per issue role. Every count equals the
// number of detail rows in that role/bucket (TDD 3.2, 8.6).
//
// Issue buckets differ from PR buckets — there is no merged — so the issue rows
// leave that column empty rather than the table being split in two, which keeps
// the summary a single view of everything tracked.
func writeSummaryTable(b *strings.Builder, submitters, reviewers []model.PR, issues []model.Issue) {
	b.WriteString("## Summary\n\n")
	b.WriteString(fmt.Sprintf("| Role | %s Open | %s Stale | %s Merged | %s Closed | Total |\n",
		sumOpen, sumStale, sumMerged, sumClosed))
	b.WriteString("|------|---------|----------|-----------|-----------|-------|\n")
	writeSummaryRow(b, "Submitter (PR)", submitters)
	writeSummaryRow(b, "Reviewer (PR)", reviewers)
	writeIssueSummaryRow(b, "Author (issue)", filterIssueRole(issues, model.IssueRoleAuthor))
	writeIssueSummaryRow(b, "Participant (issue)", filterIssueRole(issues, model.IssueRoleParticipant))
	b.WriteString("\n")
}

// writeIssueSummaryRow emits one issue summary row. The Merged column is a dash:
// an issue cannot be merged, so a zero there would imply a bucket that exists and
// happens to be empty.
func writeIssueSummaryRow(b *strings.Builder, label string, issues []model.Issue) {
	o, s, c := issueBucketCounts(issues)
	b.WriteString(fmt.Sprintf("| %s | %d | %d | — | %d | %d |\n",
		label, o, s, c, len(issues)))
}

func writeSummaryRow(b *strings.Builder, label string, prs []model.PR) {
	o, s, m, c := bucketCounts(prs)
	b.WriteString(fmt.Sprintf("| %s | %d | %d | %d | %d | %d |\n",
		label, o, s, m, c, len(prs)))
}

func bucketCounts(prs []model.PR) (open, stale, merged, closed int) {
	for _, p := range prs {
		switch p.Bucket {
		case model.BucketOpen:
			open++
		case model.BucketStale:
			stale++
		case model.BucketMerged:
			merged++
		case model.BucketClosed:
			closed++
		}
	}
	return
}

// writeSubmitterSection emits the four mutually-exclusive submitter tables in
// the established order: Open, Stale, Merged, Closed.
func writeSubmitterSection(b *strings.Builder, prs []model.PR, now time.Time) {
	if len(prs) == 0 {
		b.WriteString("_No pull requests._\n\n")
		return
	}

	open := selectBucket(prs, model.BucketOpen)
	stale := selectBucket(prs, model.BucketStale)
	merged := selectTerminalBucket(prs, model.BucketMerged)
	closed := selectTerminalBucket(prs, model.BucketClosed)

	// 💡 Open — Repo | PR | Title | Created | Age | Updated | Action Needed
	b.WriteString(fmt.Sprintf("## %s Open (%d)\n\n", secOpen, len(open)))
	if len(open) > 0 {
		b.WriteString("| Repo | PR | Title | Created | Age | Updated | Action Needed |\n")
		b.WriteString("|------|-----|-------|---------|-----|---------|----------------|\n")
		for _, p := range open {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s | %s |\n",
				escapePipes(p.Repo), prNumLink(p), escapePipes(p.Title),
				p.Created.Format(dateLayout), age(now, p.Created),
				updated(now, p.LastActivity), actionNeededCell(p)))
		}
		b.WriteString("\n")
	}

	// ☠ Stale — Repo | PR | Title | Created | Age | Updated | Reason
	b.WriteString(fmt.Sprintf("## %s Stale (%d)\n\n", secStale, len(stale)))
	if len(stale) > 0 {
		b.WriteString("| Repo | PR | Title | Created | Age | Updated | Reason |\n")
		b.WriteString("|------|-----|-------|---------|-----|---------|--------|\n")
		for _, p := range stale {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s | %s |\n",
				escapePipes(p.Repo), prNumLink(p), escapePipes(p.Title),
				p.Created.Format(dateLayout), age(now, p.Created),
				updated(now, p.LastActivity), noteCell(p)))
		}
		b.WriteString("\n")
	}

	// 📦 Merged — Repo | PR | Title | Created | Merged | Notes
	b.WriteString(fmt.Sprintf("## %s Merged (%d)\n\n", secMerged, len(merged)))
	if len(merged) > 0 {
		b.WriteString("| Repo | PR | Title | Created | Merged | Notes |\n")
		b.WriteString("|------|-----|-------|---------|--------|-------|\n")
		for _, p := range merged {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s |\n",
				escapePipes(p.Repo), prNumLink(p), escapePipes(p.Title),
				p.Created.Format(dateLayout), dateOrDash(p.MergedAt), noteCell(p)))
		}
		b.WriteString("\n")
	}

	// ⛔ Closed — Repo | PR | Title | Created | Closed | Reason
	b.WriteString(fmt.Sprintf("## %s Closed (%d)\n\n", secClosed, len(closed)))
	if len(closed) > 0 {
		b.WriteString("| Repo | PR | Title | Created | Closed | Reason |\n")
		b.WriteString("|------|-----|-------|---------|--------|--------|\n")
		for _, p := range closed {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s |\n",
				escapePipes(p.Repo), prNumLink(p), escapePipes(p.Title),
				p.Created.Format(dateLayout), dateOrDash(p.ClosedAt), noteCell(p)))
		}
		b.WriteString("\n")
	}
}

// writeReviewerSection emits the reviewer tables split by ball-holding: PRs
// awaiting our action, open PRs where our review is submitted (they hold the
// ball), and a Done table for merged/closed PRs with an outcome.
func writeReviewerSection(b *strings.Builder, prs []model.PR, now time.Time) {
	if len(prs) == 0 {
		b.WriteString("_No pull requests._\n\n")
		return
	}

	var awaitingUs, reviewSubmitted, done []model.PR
	for _, p := range prs {
		switch p.Bucket {
		case model.BucketMerged, model.BucketClosed:
			done = append(done, p)
		default: // open, stale
			if ballWithUs(p) {
				awaitingUs = append(awaitingUs, p)
			} else {
				reviewSubmitted = append(reviewSubmitted, p)
			}
		}
	}
	sortByLastActivity(awaitingUs)
	sortByLastActivity(reviewSubmitted)
	sortTerminalRows(done)

	// Awaiting Our Action — Repo | PR | Title | Updated | Our Review
	b.WriteString(fmt.Sprintf("## Awaiting Our Action (%d)\n\n", len(awaitingUs)))
	if len(awaitingUs) > 0 {
		b.WriteString("| Repo | PR | Title | Updated | Our Review |\n")
		b.WriteString("|------|-----|-------|---------|------------|\n")
		for _, p := range awaitingUs {
			// The inferred emoji takes precedence over the structural pending
			// marker: when the model supplied an emoji, the note already leads
			// with it (noteCell), so we don't also prepend ⏳ and double the
			// glyph. Fall back to the structural ⏳ only when there is no
			// inferred emoji (including the note-less "Awaiting our review").
			var review string
			n := noteCell(p)
			switch {
			case p.Emoji != "":
				review = n // note already emoji-prefixed
			case n != unavailableNote:
				review = markPending + " " + n
			default:
				review = markPending + " Awaiting our review"
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
				escapePipes(p.Repo), prNumLink(p), escapePipes(p.Title),
				updated(now, p.LastActivity), review))
		}
		b.WriteString("\n")
	}

	// 💡 Open — Review Submitted — Repo | PR | Title | Updated | Our Review
	b.WriteString(fmt.Sprintf("## %s Open — Review Submitted (%d)\n\n", secOpen, len(reviewSubmitted)))
	if len(reviewSubmitted) > 0 {
		b.WriteString("| Repo | PR | Title | Updated | Our Review |\n")
		b.WriteString("|------|-----|-------|---------|------------|\n")
		for _, p := range reviewSubmitted {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
				escapePipes(p.Repo), prNumLink(p), escapePipes(p.Title),
				updated(now, p.LastActivity), noteCell(p)))
		}
		b.WriteString("\n")
	}

	// ✅ Done - Closed / Merged — Repo | PR | Title | Outcome | Notes
	b.WriteString(fmt.Sprintf("## %s Done - Closed / Merged (%d)\n\n", sumMerged, len(done)))
	if len(done) > 0 {
		b.WriteString("| Repo | PR | Title | Outcome | Notes |\n")
		b.WriteString("|------|-----|-------|---------|-------|\n")
		for _, p := range done {
			outcome := outcomeClosed
			if p.Bucket == model.BucketMerged {
				outcome = outcomeMerged
			} else if p.CloseReason.Valid() && !p.Unverified {
				// Surface the close sub-reason on the reviewer side too (TDD
				// 3.1), e.g. "🚪 CLOSED / ♻️ superseded". The sub-reason carries a
				// deterministic per-enum emoji (not LLM-inferred). Merged carries
				// no sub-reason; an unverified row's reason is a non-authoritative
				// default, so it is not shown.
				sub := string(p.CloseReason)
				if e := closeReasonEmoji[p.CloseReason]; e != "" {
					sub = e + " " + sub
				}
				outcome = fmt.Sprintf("%s / %s", outcomeClosed, sub)
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
				escapePipes(p.Repo), prNumLink(p), escapePipes(p.Title), outcome, noteCell(p)))
		}
		b.WriteString("\n")
	}
}

// ballWithUs reports whether an open *reviewer* PR is awaiting our action (we owe
// a review) rather than the author's. A PR waiting on a reviewer to act, or
// unassigned, holds the ball on us; anything else (author iterating, changes
// requested of the author, blocked externally, merge-ready) is on them.
//
// The CI flag is deliberately not consulted here: it is submitter-scoped, so it is
// always false on the reviewer PRs this function sees. A submitter PR's
// ball-holding is not expressed by a table split — the submitter section is
// bucketed, not split by who owes the next move — so a red build surfaces there
// through the 🚧 mark on its Action Needed cell instead (TDD 4.12).
func ballWithUs(p model.PR) bool {
	return p.Action == model.ActionAwaitingReview || p.Action == model.ActionUnassigned
}

// actionNeededCell renders the submitter Open "Action Needed" cell: the
// inferred note, led by either the model's emoji or a structural marker
// (⏳ pending-not-us vs 🔄 active back-and-forth).
func actionNeededCell(p model.PR) string {
	marker := markPending
	switch p.Action {
	case model.ActionAuthorActive, model.ActionChangesRequested, model.ActionMergeReady,
		model.ActionConflicted, model.ActionMergeBlocked, model.ActionReviewFeedback:
		marker = markBackForth
	}
	note := p.Companion
	if note == "" {
		note = "action needed"
	}
	if p.Action == model.ActionConflicted {
		// Surface the conflict explicitly even alongside the inferred note.
		note = "merge conflict — " + note
	}
	if p.Action == model.ActionMergeBlocked {
		// Surface the block explicitly: GitHub's own mergeable_state says this
		// cannot merge, which the inferred note (possibly still "approved,
		// ready to merge" from before the block appeared) would otherwise
		// contradict.
		note = "blocked from merging — " + note
	}
	if p.Action == model.ActionReviewFeedback {
		// Surface the outstanding feedback explicitly: the inferred note may
		// read as "conditionally approved" when comments are still open, which
		// would wrongly suggest the ball is elsewhere (TDD 4.9).
		note = "unresolved review feedback — " + note
	}
	note = withEmoji(p, note)
	// The inferred emoji takes precedence over the structural marker: when the
	// model supplied one, withEmoji already prefixed the note, so prepending
	// the marker too would double the glyph (e.g. "⏳ ⏳ ..."). Use the
	// structural marker only when there is no inferred emoji.
	cell := note
	if p.Emoji == "" {
		cell = marker + " " + note
	}
	// The CI flag is orthogonal to the action, so its mark is *added* rather than
	// substituted — the row shows both facts (TDD 4.11). It leads, being the hard
	// fact. Suppressed when the inferred emoji is already the same glyph, so the
	// row never renders 🚧 twice.
	if p.CIFailing && p.Emoji != markCIFailing {
		cell = markCIFailing + " " + cell
	}
	if p.Unverified {
		cell += " ⚠️ unverified"
	}
	return withElevated(p, cell)
}

// noteCell renders a plain note cell (Reason / Notes / Review Submitted) from
// the inferred companion, with the unavailable marker and unverified flag. The
// model-inferred emoji prefixes the note when present.
func noteCell(p model.PR) string {
	note := p.Companion
	if note == "" {
		note = unavailableNote
	} else {
		note = withEmoji(p, note)
	}
	if p.Unverified {
		note += " ⚠️ unverified"
	}
	return withElevated(p, note)
}

// withEmoji prefixes the model-inferred emoji to a note when one is present.
// The emoji is decorative and validated at the provider boundary; an absent
// emoji (unverified or notes skipped) leaves the note unprefixed.
func withEmoji(p model.PR, note string) string {
	if p.Emoji == "" {
		return note
	}
	return p.Emoji + " " + note
}

// withElevated prefixes the elevated-priority marker so elevated rows are
// visibly distinguished (TDD 3.5).
func withElevated(p model.PR, cell string) string {
	if p.Priority == model.PriorityElevated {
		return elevatedMarker + cell
	}
	return cell
}

// prNumLink renders the "[#N](url)" PR column used by the model.
func prNumLink(p model.PR) string {
	return fmt.Sprintf("[#%d](%s)", p.Number, p.URL)
}

// age renders the whole-day age of a PR relative to now (e.g. "13d").
func age(now, created time.Time) string {
	d := now.Sub(created)
	days := int(d.Hours() / 24)
	if days < 0 {
		days = 0
	}
	return fmt.Sprintf("%dd", days)
}

// updated renders how long ago an item last saw activity, in the same whole-day
// form as age. An unknown activity date renders as a dash rather than a computed
// number: a zero timestamp would otherwise print an absurd age, and a store
// written before last_activity was persisted legitimately has none for items
// nothing will re-crawl.
func updated(now, lastActivity time.Time) string {
	if lastActivity.IsZero() {
		return "—"
	}
	return age(now, lastActivity)
}

// dateOrDash formats an optional timestamp, or a dash when absent.
func dateOrDash(t *time.Time) string {
	if t == nil {
		return "—"
	}
	return t.Format(dateLayout)
}

func selectBucket(prs []model.PR, bucket model.Bucket) []model.PR {
	var out []model.PR
	for _, p := range prs {
		if p.Bucket == bucket {
			out = append(out, p)
		}
	}
	sortByLastActivity(out)
	return out
}

// selectTerminalBucket is selectBucket for a terminal bucket (Merged, Closed):
// rows are ordered by terminal date rather than repo/number (TDD 3.6).
func selectTerminalBucket(prs []model.PR, bucket model.Bucket) []model.PR {
	var out []model.PR
	for _, p := range prs {
		if p.Bucket == bucket {
			out = append(out, p)
		}
	}
	sortTerminalRows(out)
	return out
}

func filterRole(prs []model.PR, role model.Role) []model.PR {
	var out []model.PR
	for _, p := range prs {
		if p.Role == role {
			out = append(out, p)
		}
	}
	return out
}

// sortByLastActivity orders rows by LastActivity descending (most recently
// updated first), so every live PR table (submitter Open/Stale, reviewer
// Awaiting Our Action, reviewer Open — Review Submitted) surfaces the PR that
// moved most recently — the one most likely to need a fresh look — ahead of
// one that has sat quietly. Elevated priority still sorts first, matching
// every other table (3.5); a tie (including two rows sharing an unknown
// activity date) falls back to the repo/number order used elsewhere.
func sortByLastActivity(rows []model.PR) {
	sort.SliceStable(rows, func(i, j int) bool {
		ei := rows[i].Priority == model.PriorityElevated
		ej := rows[j].Priority == model.PriorityElevated
		if ei != ej {
			return ei // elevated first
		}
		ai, aj := rows[i].LastActivity, rows[j].LastActivity
		if !ai.Equal(aj) {
			return ai.After(aj) // most recently updated first
		}
		if rows[i].Repo != rows[j].Repo {
			return rows[i].Repo < rows[j].Repo
		}
		return rows[i].Number < rows[j].Number
	})
}

// terminalDate returns the timestamp at which a PR reached its terminal state
// — MergedAt for a merged PR, ClosedAt for a closed one — or the zero time if
// neither is set (a record written before either field existed). It mirrors
// store.terminalTime for the same concept, kept as a separate render-local
// helper since store's version is unexported and scoped to the merge path.
func terminalDate(p model.PR) time.Time {
	if p.MergedAt != nil {
		return *p.MergedAt
	}
	if p.ClosedAt != nil {
		return *p.ClosedAt
	}
	return time.Time{}
}

// sortTerminalRows orders a terminal bucket (Merged, Closed, or the reviewer
// Done table mixing both) by most-recent-first terminal date, so the newest
// completed item always leads (TDD 3.6). Elevated priority still sorts first,
// matching sortByLastActivity, since a flagged row should stand out regardless
// of age.
// Rows sharing a terminal date (including two zero-value dates on
// pre-migration records) fall back to the repo/number order for a stable,
// deterministic result.
func sortTerminalRows(rows []model.PR) {
	sort.SliceStable(rows, func(i, j int) bool {
		ei := rows[i].Priority == model.PriorityElevated
		ej := rows[j].Priority == model.PriorityElevated
		if ei != ej {
			return ei // elevated first
		}
		ti, tj := terminalDate(rows[i]), terminalDate(rows[j])
		if !ti.Equal(tj) {
			return ti.After(tj) // most recent first
		}
		if rows[i].Repo != rows[j].Repo {
			return rows[i].Repo < rows[j].Repo
		}
		return rows[i].Number < rows[j].Number
	})
}

// escapePipes escapes table-breaking pipe characters in cell text.
func escapePipes(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
